workflows:
  ios-app-store:
    name: iOS App Store Production
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: "app-store-connect"

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.seba.haltercalc

      groups:
        - app_store_credentials

    scripts:
      - name: Flutter clean & get
        script: |
          flutter clean
          flutter pub get

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

      email:
        recipients:
          - seba.muller@hotmail.cl
        notify:
          success: true
          failure: true
