workflows:
  ios-app-store:
    name: iOS App Store Production
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "SebaHalt" # <--- ESTO ES LO QUE FALTA
    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace" 
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Flutter clean & get
        script: |
          flutter clean
          flutter pub get
      - name: Set up code signing settings on Xcode project
        script: |
          # Esto descarga los perfiles de Apple usando tu API Key
          xcode-project use-profiles
      - name: Build iOS for Distribution
        script: |
          # Generamos el archivo de exportación manualmente para evitar errores
          cat <<EOF > $HOME/export_options.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>T69RZR8Y5K</string>
              <key>uploadBitcode</key>
              <false/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF

          # Compilamos usando el archivo que acabamos de crear
          flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration 
        submit_to_testflight: true
      email:
        recipients:
          - seba.muller@hotmail.cl
        notify:
          success: true
          failure: true
